# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [2]:
import numpy as np

In [3]:
# ejercicio 1
# se usó el np.all para ver si todos los valores son True
arreglo_cero= (np.random.randint(0, 10, size=[10,10]))
print(arreglo_cero)
indices_ceros = np.all(arreglo_cero != 0)
print ("¿El resultado no tiene ceros ? ", indices_ceros)
        

[[5 4 0 4 1 2 3 1 7 2]
 [3 4 5 1 1 1 7 8 2 9]
 [1 4 9 9 9 3 1 4 0 7]
 [4 0 5 1 0 4 6 4 3 0]
 [2 1 3 6 2 5 9 4 4 9]
 [6 5 0 9 3 6 6 5 0 4]
 [8 1 9 8 3 2 1 6 2 3]
 [7 5 1 7 8 0 8 3 2 7]
 [8 4 5 3 5 2 0 2 8 9]
 [3 3 0 0 9 4 8 3 8 4]]
¿El resultado no tiene ceros ?  False


In [4]:
# ejercicio 2 Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
# np.any es para ver si en algun elemento es diferente a 0
arreglo_cero= (np.random.randint(0, 10, size=[10,10]))
print(arreglo_cero)
indices_ceros = np.any(arreglo_cero !=0)
print ("¿El resultado contiene algún elemento que no sea cero ? ", indices_ceros)
        

[[1 3 0 6 1 2 8 6 2 6]
 [9 2 6 2 5 3 2 6 6 0]
 [9 6 0 5 3 7 2 0 1 8]
 [1 0 2 2 2 5 5 3 7 1]
 [3 3 4 8 5 2 0 8 2 1]
 [3 6 6 8 0 6 2 8 6 1]
 [4 4 1 8 4 2 9 1 9 1]
 [2 8 0 9 0 7 3 5 7 4]
 [7 7 2 3 5 9 2 1 4 0]
 [8 0 2 0 2 1 5 0 7 5]]
¿El resultado contiene algún elemento que no sea cero ?  True


In [5]:
# ejercicio 3 Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
arreglo_cero= (np.random.randint(0, 10, size=[5,5]))
print(arreglo_cero)
arreglo_cero = np.array([1, 2, np.nan, np.inf])
infinito= arreglo_cero = np.inf  # infinito
print(infinito)
valor_no_numerico= np.nan  # no es un número
print(valor_no_numerico)

[[3 9 6 4 1]
 [3 7 8 4 7]
 [1 7 4 1 7]
 [9 5 5 3 3]
 [8 0 2 6 7]]
inf
nan


In [14]:
#Ejercicio 4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
a = np.array([1, 2, np.inf])
infinito = np.isinf(a)

print(infinito)
print("¿El arreglo contiene infinitos?:", np.any(infinito))

[False False  True]
¿El arreglo contiene infinitos?: True


In [15]:
# Ejercicio 5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
a = np.array([1, np.nan, 3])

tiene_nan = np.isnan(a)

print(tiene_nan)
print("¿El arreglo contiene NaN?:", np.any(tiene_nan))

[False  True False]
¿El arreglo contiene NaN?: True


In [16]:
#Ejercicio 6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

mayor = a > b
mayor_igual = a >= b
menor = a < b
menor_igual = a <= b

print("a > b:", mayor)
print("a >= b:", mayor_igual)
print("a < b:", menor)
print("a <= b:", menor_igual)

a > b: [False False  True]
a >= b: [False  True  True]
a < b: [ True False False]
a <= b: [ True  True False]


In [ ]:
#Ejercicio 7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.

a = np.array([1, 7, 13, 105])

memoria = a.nbytes

print("Arreglo:", a)
print("Memoria ocupada:", memoria, "bytes")

Arreglo: [  1   7  13 105]
Memoria ocupada: 32 bytes


In [18]:
#Ejercicio 8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.

ceros = np.zeros(10)


unos = np.ones(10)


cincos = np.full(10, 5)

print("Ceros:", ceros)
print("Unos:", unos)
print("Cincos:", cincos)

Ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Cincos: [5 5 5 5 5 5 5 5 5 5]


In [19]:
#Ejercicio 9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
a = np.arange(30, 71)

print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [20]:
#Ejercicio 10. Crea un arreglo que contenga los números pares entre 30 y 70.
a = np.arange(30, 71, 2)

print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [21]:
#Ejercicio 11. Crea una matriz identidad de 3x3.

I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
#Ejercicio 12. Genera un número aleatorio entre 0 y 1.

num = np.random.rand()

print(num)

0.7978835674599128


In [23]:
#Ejercicio 13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
a = np.random.randn(15)

print(a)

[ 0.31902647  1.19613422 -0.06107498 -0.59330936 -0.81410929 -0.65874876
  0.71248836 -0.38694429 -0.0577271   0.55396143 -0.28764779  0.76979299
  0.97170977  1.30624162  1.5174346 ]


In [24]:
#Ejercicio 14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
a = np.arange(15, 56)   

print(a[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [25]:
#Ejercicio 15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
a = np.linspace(5, 50, 10)

print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [26]:
#Ejercicio 16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
a = np.arange(0, 21)

a[9:16] = -a[9:16]

print(a)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [27]:
#Ejercicio 17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
a = np.array([1, 2, 3])

lista = a.tolist()

print(lista)

[1, 2, 3]


In [28]:
#Ejercicio 18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
l = [1, 2, 3]

a = np.array(l)

print(a)

[1 2 3]


In [29]:
#Ejercicio 19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
m = np.array([[1, 2],
              [3, 4]])

pares = (m % 2 == 0)

print(pares)

[[False  True]
 [False  True]]


In [30]:
# ejercicio 20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.
m = np.array([[1, 2, 3],
              [4, 5, 6]])

filas, columnas = m.shape

print("Filas:", filas)
print("Columnas:", columnas)

Filas: 2
Columnas: 3
